# Example configuration for IWF JSON Request Check Bundle
iwf_json_request_check:
  # Default size limit for JSON requests in bytes
  default_max_content_length: '%env(int:IWF_JSON_REQUEST_CHECK_DEFAULT_MAX_LENGTH)%'