name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "Stale issue"
          stale-pr-message: "Stale pull request"
          close-issue-message: "Stale issue closed"
          close-pr-message: "Stale pull request closed"
          stale-issue-label: "no-issue-activity"
          exempt-issue-labels: "awaiting-approval,work-in-progress"
          stale-pr-label: "no-pr-activity"
          exempt-pr-labels: "awaiting-approval,work-in-progress"
          only-labels: "awaiting-feedback,awaiting-answers"
